menu:
  - name: dashboard.dashboard
    data-ajax-source: "/main"
    data-ajax-method: "replaceHtml"
    data-ajax-container: "span#content-wrapper"
    icon: "ri-home-smile-line"
    class: "active"
  - name: dashboard.calendar
    data-ajax-source: "/calendar"
    data-ajax-method: "replaceHtml"
    data-ajax-container: "span#content-wrapper"
    icon: "ri-calendar-todo-line"
  - name: dashboard.medical_history
    data-ajax-source: "/medical-history"
    data-ajax-method: "replaceHtml"
    data-ajax-container: "span#content-wrapper"
    icon: "ri-file-list-3-line"
  - name: dashboard.patients
    data-ajax-source: "/patients"
    data-ajax-method: "replaceHtml"
    data-ajax-container: "span#content-wrapper"
    icon: "ri-user-heart-line"
  - name: dashboard.chat
    data-ajax-source: "/chat"
    data-ajax-method: "replaceHtml"
    data-ajax-container: "span#content-wrapper"
    icon: "ri-chat-1-line"


  