menu:
  - name: Dashboard
    data-ajax-source: "/main"
    data-ajax-method: "replaceHtml"
    data-ajax-container: "span#content-wrapper"
    icon: "ri-home-smile-line"
    class: "active"
  - name: Calendar
    data-ajax-source: "/calendar"
    data-ajax-method: "replaceHtml"
    data-ajax-container: "span#content-wrapper"
    icon: "ri-calendar-todo-line"
  - name: Medical History
    data-ajax-source: "/medical-history"
    data-ajax-method: "replaceHtml"
    data-ajax-container: "span#content-wrapper"
    icon: "ri-file-list-3-line"
  - name: Patients
    data-ajax-source: "/patients"
    data-ajax-method: "replaceHtml"
    data-ajax-container: "span#content-wrapper"
    icon: "ri-user-heart-line"
  - name: Specialties
    data-ajax-source: "/specialty"
    data-ajax-method: "replaceHtml"
    data-ajax-container: "span#content-wrapper"
    icon: "ri-stethoscope-line"
  - name: Doctors
    data-ajax-source: "/doctors"
    data-ajax-method: "replaceHtml"
    data-ajax-container: "span#content-wrapper"
    icon: "ri-user-3-line"
  - name: Settings
    data-ajax-source: "/settings"
    data-ajax-method: "replaceHtml"
    data-ajax-container: "span#content-wrapper"
    icon: "ri-settings-3-line"
  