data:
  name: "Users"
  id: "user_table"
  path: '/users/data'
  file: 'user'
  actions:
    - class: btn-edit
      icon: edit
      data:
        data-ajax-source: /users/form/{0}
        data-ajax-method: replaceHtml
        data-ajax-container: '#offcanvasEnd'
        data-bs-toggle: "offcanvas" 
        data-bs-target: "#offcanvasEnd"
        aria-controls: "offcanvasEnd"
        action: edit
    - class: btn-delete
      icon: delete-bin-5
      data:
        data-ajax-source: /users/delete/{0}
        data-ajax-method: replaceHtml
        data-ajax-container: 'span#content-wrapper'
        data-ajax-then: afterSaveCallback
        action: delete
      dropdown: false
    - dropdown: true
      options:
      - label: View Details
        data:
          data-ajax-source: /users/view/{0}
          data-ajax-method: replaceHtml
          data-ajax-container: '#offcanvasEnd'
          data-bs-toggle: "offcanvas" 
          data-bs-target: "#offcanvasEnd"
          aria-controls: "offcanvasEnd"
          action: view
      - label: Send Email
        data:
          id: 1
          action: email"
  headers:
  - name: "id"
    key: "id"
    orderable: true
    searchable: true
    visible: true
  - name: "name"
    key: "firstname"
    orderable: true
    searchable: true
    visible: true
  - name: "lastname"
    key: "lastname"
    orderable: true
    searchable: true
    visible: false
  - name: "email"
    key: "email"
    orderable: true
    searchable: true
    visible: true
  - name: status
    key: status_name
    orderable: true
    searchable: true
    visible: true
  - name: 'actions'
    key: "actions"
    orderable: false
    searchable: false
    visible: true
    actions:
      - name: "View"
        icon: "ri-eye-line"
        action: "view"
      - name: "Edit"
        icon: "ri-pencil-line"
        action: "edit"
      - name: "Delete"
        icon: "ri-delete-bin-line"
        action: "delete"