inputs:
  - type: hidden
    name: id
    value: 0
    col: 12
  - type: text
    name: title
    label: title_form
    value: ''
    col: 12
    placeholder: Title
  - type: text
    name: description
    label: description
    value: ''
    col: 12
    placeholder: Description
  - type: date
    name: date
    label: date
    value: ''
    col: 6
  - type: time
    name: time
    label: time
    value: ''
    col: 6
  - type: text
    name: identifier
    label: patient_indentification
    data:
      fs-validate: "true"
      fs-number: "true"
      fs-minlength: "7"
      fs-maxlength: "8"
      fs-error-minlength: calendar.identification_error_minlength
      fs-error-maxlength: calendar.identification_error_maxlength
      fs-error-number: calendar.identification_error_numeric
    value: ''
    checker: /patients/checkidentifier
    minlength: "7"
    container: '["#firstname", "#lastname"]'
    method: replaceValue
    col: 12
  - type: text
    name: firstname
    label: firstname
    value: ''
    col: 6
  - type: text
    name: lastname
    label: lastname
    value: ''
    col: 6
form:
  id: 'event_form'
  file: 'calendar'
  title: add_event
  source: /calendar/save
  method: replaceHtml
  container: 'span#content-wrapper'
  then: afterSaveCallback