table:
  name: "Doctors"
  id: "doctor_table"
  path: '/doctors/data'
  file: 'doctors'
  actions:
    - class: btn-edit
      icon: edit
      data:
        data-ajax-source: /doctors/form/{0}
        data-ajax-method: replaceHtml
        data-ajax-container: '#offcanvasEnd'
        data-bs-toggle: "offcanvas" 
        data-bs-target: "#offcanvasEnd"
        aria-controls: "offcanvasEnd"
        action: edit
    - class: btn-delete
      icon: delete-bin-5
      data:
        data-ajax-source: /doctors/delete/{0}
        data-ajax-method: replaceHtml
        data-ajax-container: 'span#content-wrapper'
        data-ajax-then: afterSaveCallback
        action: delete
      dropdown: false
    - dropdown: true
      options:
      - label: View Details
        data:
          data-ajax-source: /doctors/view/{0}
          data-ajax-method: replaceHtml
          data-ajax-container: '#offcanvasEnd'
          data-bs-toggle: "offcanvas" 
          data-bs-target: "#offcanvasEnd"
          aria-controls: "offcanvasEnd"
          action: view
      - label: Send Email
        data:
          id: 1
          action: email"
  headers:
  - name: "doctor_id"
    key: "id"
    orderable: true
    searchable: true
    visible: true
  - name: "firstname"
    key: "firstname"
    orderable: true
    searchable: true
    visible: true
  - name: "lastname"
    key: "lastname"
    orderable: true
    searchable: true
    visible: true
  - name: "email"
    key: "email"
    orderable: true
    searchable: true
    visible: true
  - name: status
    key: status_name
    orderable: true
    searchable: true
    visible: true
  - name: 'actions'
    key: "actions"
    orderable: false
    searchable: false
    visible: true
    actions:
      - name: "View"
        icon: "ri-eye-line"
        action: "view"
      - name: "Edit"
        icon: "ri-pencil-line"
        action: "edit"
      - name: "Delete"
        icon: "ri-delete-bin-line"
        action: "delete"
inputs:
  - type: hidden
    name: id
    value: 0
    col: 12
  - type: text
    name: firstname
    label: firstname
    value: ''
    col: 6
    placeholder: John
  - type: text
    name: lastname
    label: lastname
    value: ''
    placeholder: Doe
    col: 6
  - type: date
    name: date_of_birth
    label: date_of_birth
    value: ''
    col: 12
  - type: email
    name: email
    label: email
    value: ''
    col: 12
  - type: select
    name: specialty
    label: specialty
    value: ''
    url: '/specialty/list'
    multiple: "true"
    col: 12
  - type: text
    name: phone
    label: phone
    value: ''
    col: 12
  - type: text
    name: address
    label: address
    value: ''
    col: 12
  - type: text
    name: city
    label: city
    value: ''
    col: 6
  - type: text
    name: state
    label: state
    value: ''
    col: 6
  - type: text
    name: country
    label: country
    value: ''
    col: 6
  - type: text
    name: zip
    label: zip_code
    value: ''
    col: 6
  - type: text
    name: identifier
    label: identifier
    value: ''
    col: 12
form:
  id: 'doctor_form'
  title: add_doctor
  file: 'doctors'
  source: /doctors/save
  method: replaceHtml
  container: 'span#content-wrapper'
  then: afterSaveCallback