table:
  name: "Doctors"
  id: "doctor_table"
  path: '/doctors/data'
  file: 'doctors'
  actions:
    - class: btn-edit
      icon: edit
      data:
        data-ajax-source: /doctors/form/{0}
        data-ajax-method: replaceHtml
        data-ajax-container: '#offcanvasEnd'
        data-bs-toggle: "offcanvas" 
        data-bs-target: "#offcanvasEnd"
        aria-controls: "offcanvasEnd"
        action: edit
    - class: btn-delete
      icon: delete-bin-5
      data:
        data-ajax-source: /doctors/delete/{0}
        data-ajax-method: replaceHtml
        data-ajax-container: 'span#content-wrapper'
        data-ajax-then: afterSaveCallback
        action: delete
      dropdown: false
    - dropdown: true
      options:
      - label: Set hours
        data:
          data-ajax-source: /doctors/sethours/{0}
          data-ajax-method: replaceHtml
          data-ajax-container: '#offcanvasEnd'
          data-bs-toggle: "offcanvas" 
          data-bs-target: "#offcanvasEnd"
          aria-controls: "offcanvasEnd"
          action: view
      - label: Send Email
        data:
          id: 1
          action: email"
  headers:
  - name: "doctor_id"
    key: "id"
    orderable: true
    searchable: true
    visible: true
  - name: "firstname"
    key: "firstname"
    orderable: true
    searchable: true
    visible: true
  - name: "lastname"
    key: "lastname"
    orderable: true
    searchable: true
    visible: true
  - name: "email"
    key: "email"
    orderable: true
    searchable: true
    visible: true
  - name: status
    key: status_name
    orderable: true
    searchable: true
    visible: true
  - name: 'actions'
    key: "actions"
    orderable: false
    searchable: false
    visible: true
    actions:
      - name: "View"
        icon: "ri-eye-line"
        action: "view"
      - name: "Edit"
        icon: "ri-pencil-line"
        action: "edit"
      - name: "Delete"
        icon: "ri-delete-bin-line"
        action: "delete"
inputs:
  - type: hidden
    name: id
    value: 0
    col: 12
  - type: text
    name: firstname
    label: firstname
    value: ''
    col: 6
    placeholder: John
    data:
      fs-validate: "true"
      fs-required: "true"
      fs-minlength: 3
      fs-error-required: user.firstname_required
      fs-error-minlength: user.firstname_minlength
  - type: text
    name: lastname
    label: lastname
    value: ''
    placeholder: Doe
    col: 6
    data:
      fs-validate: "true"
      fs-required: "true"
      fs-minlength: 3
      fs-error-required: user.lastname_required
      fs-error-minlength: user.lastname_minlength
  - type: date
    name: date_of_birth
    label: date_of_birth
    value: ''
    col: 12
  - type: email
    name: email
    label: email
    value: ''
    col: 12
    data:
      fs-validate: "true"
      fs-required: "true"
      fs-email: "true"
      fs-remote: "true"
      fs-error-required: user.email_required
      fs-error-email: user.email_invalid
  - type: select
    name: specialties
    label: specialty
    value: ''
    selected_data: ''
    url: '/specialty/list'
    multiple: "true"
    col: 12
  - type: text
    name: phone
    label: phone
    value: ''
    col: 12
  - type: text
    name: address
    label: address
    value: ''
    col: 12
  - type: text
    name: city
    label: city
    value: ''
    col: 6
  - type: text
    name: state
    label: state
    value: ''
    col: 6
  - type: text
    name: country
    label: country
    value: ''
    col: 6
  - type: text
    name: zip
    label: zip_code
    value: ''
    col: 6
  - type: text
    name: identifier
    label: identifier
    value: ''
    col: 12
    data:
      fs-validate: "true"
      fs-number: "true"
      fs-required: "true"
      fs-minlength: "7"
      fs-maxlength: "8"
      fs-error-required: patient.identifier_required
      fs-error-minlength: patient.identifier_minlength
      fs-error-maxlength: patient.identifier_maxlength
      fs-error-number: patient.identifier_number
form:
  id: 'doctor_form'
  title: add_doctor
  file: 'doctors'
  source: /doctors/save
  method: replaceHtml
  container: 'span#content-wrapper'
  then: afterSaveCallback
inputs_hours:
  - type: hidden
    name: id
    value: 0
    col: 12
  - type: hidden
    name: doctor_id
    value: 0
    col: 12
  - type: select
    name: specialties
    label: specialty
    value: ''
    selected_data: ''
    checker: /doctors/checkspecialty
    method: replaceValue
    container: 'id'
    options: ''
    col: 12
  - type: select
    name: days
    label: days
    value: ''
    selected_data: ''
    options: 
      - value: 1
        text: "Monday"
      - value: 2
        text: "Tuesday"
      - value: 3
        text: "Wednesday"
      - value: 4
        text: "Thursday"
      - value: 5
        text: "Friday"
      - value: 6
        text: "Saturday"
      - value: 7
        text: "Sunday"
    multiple: "true"
    col: 12
  - type: time
    name: start_time
    label: start_time
    value: ''
    col: 6
  - type: time
    name: end_time
    label: end_time
    value: ''
    col: 6
form_hours:
  id: 'doctor_hour_form'
  title: add_doctor
  file: 'doctors'
  source: /doctors/savehours
  method: replaceHtml
  container: 'span#content-wrapper'
  then: afterSaveCallback