table:
  name: "Patients"
  id: "patient_table"
  path: '/patients/data'
  file: 'patient'
  actions:
    - class: btn-edit
      icon: edit
      data:
        data-ajax-source: /patients/form/{0}
        data-ajax-method: replaceHtml
        data-ajax-container: '#offcanvasEnd'
        data-bs-toggle: "offcanvas" 
        data-bs-target: "#offcanvasEnd"
        aria-controls: "offcanvasEnd"
        action: edit
      dropdown: false
    - class: btn-delete
      icon: delete-bin-5
      data:
        data-ajax-source: /patients/delete/{0}
        data-ajax-method: replaceHtml
        data-ajax-container: 'span#content-wrapper'
        data-ajax-then: afterSaveCallback
        action: delete
      dropdown: false
    - dropdown: true
      options:
      - label: View Details
        data:
          action: view
      - label: Send Email
        data:
          action: email"
  headers:
  - name: "patient_id"
    key: "id"
    orderable: true
    searchable: true
    visible: true
  - name: "firstname"
    key: "firstname"
    orderable: true
    searchable: true
    visible: true
  - name: "lastname"
    key: "lastname"
    orderable: true
    searchable: true
    visible: true
  - name: "identifier"
    key: "identifier"
    orderable: true
    searchable: false
    visible: true
  - name: 'email'
    key: "email"
    orderable: true
    searchable: true
    visible: true
  - name: 'status'
    key: "status_name"
    orderable: true
    searchable: true
    visible: true
  - name: 'actions'
    key: "actions"
    orderable: false
    searchable: false
    visible: true
    actions:
      - name: "View"
        icon: "ri-eye-line"
        action: "view"
      - name: "Edit"
        icon: "ri-pencil-line"
        action: "edit"
      - name: "Delete"
        icon: "ri-delete-bin-line"
        action: "delete"
inputs:
  - type: hidden
    name: id
    value: 0
    col: 12
  - type: text
    name: firstname
    label: firstname
    data:
      fs-validate: "true"
      fs-required: "true"
      fs-minlength: 3
      fs-error-required: patient.firstname_required
      fs-error-minlength: patient.firstname_minlength
    value: ''
    col: 6
    placeholder: John
  - type: text
    name: lastname
    label: lastname
    data:
      fs-validate: "true"
      fs-required: "true"
      fs-minlength: 3
      fs-error-required: patient.lastname_required
      fs-error-minlength: patient.lastname_minlength
    value: ''
    placeholder: Doe
    col: 6
  - type: date
    name: date_of_birth
    label: date_of_birth
    value: ''
    col: 12
  - type: email
    name: email
    label: email
    data:
      fs-validate: "true"
      fs-required: "true"
      fs-email: "true"
      fs-remote: "true"
      fs-error-required: patient.email_required
      fs-error-email: patient.email_invalid
    value: ''
    col: 12
  - type: text
    name: phone
    label: phone
    value: ''
    col: 12
  - type: text
    name: address
    label: address
    value: ''
    col: 12
  - type: text
    name: city
    label: city
    value: ''
    col: 6
  - type: text
    name: state
    label: state
    value: ''
    col: 6
  - type: text
    name: country
    label: country
    value: ''
    col: 6
  - type: text
    name: zip
    label: zip_code
    value: ''
    col: 6
  - type: text
    name: identifier
    label: identifier
    data:
      fs-validate: "true"
      fs-number: "true"
      fs-required: "true"
      fs-minlength: "7"
      fs-maxlength: "8"
      fs-error-required: patient.identifier_required
      fs-error-minlength: patient.identifier_minlength
      fs-error-maxlength: patient.identifier_maxlength
      fs-error-number: patient.identifier_number
    value: ''
    col: 12
form:
  id: 'patient_form'
  title: add_patient
  file: 'patient'
  source: /patients/save
  method: replaceHtml
  container: 'span#content-wrapper'
  then: afterSaveCallback