table:
  name: "Specialties"
  id: "specialty_table"
  path: '/specialty/data'
  file: 'specialty'
  actions:
    - class: btn-edit
      icon: edit
      data:
        data-ajax-source: /specialty/form/{0}
        data-ajax-method: replaceHtml
        data-ajax-container: '#offcanvasEnd'
        data-bs-toggle: "offcanvas" 
        data-bs-target: "#offcanvasEnd"
        aria-controls: "offcanvasEnd"
        action: edit
    - class: btn-delete
      icon: delete-bin-5
      data:
        data-ajax-source: /specialty/delete/{0}
        data-ajax-method: replaceHtml
        data-ajax-container: 'span#content-wrapper'
        data-ajax-then: afterSaveCallback
        action: delete
      dropdown: false
    - dropdown: true
      options:
      - label: View Details
        data:
          data-ajax-source: /specialty/view/{0}
          data-ajax-method: replaceHtml
          data-ajax-container: '#offcanvasEnd'
          data-bs-toggle: "offcanvas" 
          data-bs-target: "#offcanvasEnd"
          aria-controls: "offcanvasEnd"
          action: view
      - label: Send Email
        data:
          id: 1
          action: email"
  headers:
  - name: "ID"
    key: "id"
    orderable: true
    searchable: true
    visible: true
  - name: "Name"
    key: "name"
    orderable: true
    searchable: true
    visible: true
  - name: Status
    key: status_name
    orderable: true
    searchable: true
    visible: true
  - name: 'actions'
    key: "actions"
    orderable: false
    searchable: false
    visible: true
    actions:
      - name: "View"
        icon: "ri-eye-line"
        action: "view"
      - name: "Edit"
        icon: "ri-pencil-line"
        action: "edit"
      - name: "Delete"
        icon: "ri-delete-bin-line"
        action: "delete"
inputs:
  - type: hidden
    name: id
    value: 0
    col: 12
  - type: text
    name: name
    label: Name
    value: ''
    placeholder: Dentistry
    col: 12
form:
  id: 'specialty_form'
  title: Add specialty
  file: 'specialty'
  source: /specialty/save
  method: replaceHtml
  container: 'span#content-wrapper'
  then: afterSaveCallback