table:
  name: "Statuses"
  id: "statuses_table"
  path: '/statuses/data'
  file: 'statuses'
  actions:
    - class: btn-edit
      icon: edit
      data:
        data-ajax-source: /statuses/form/{0}
        data-ajax-method: replaceHtml
        data-ajax-container: '#offcanvasEnd'
        data-bs-toggle: "offcanvas" 
        data-bs-target: "#offcanvasEnd"
        aria-controls: "offcanvasEnd"
        action: edit
      dropdown: false
    - class: btn-delete
      icon: delete-bin-5
      data:
        data-ajax-source: /statuses/delete/{0}
        data-ajax-method: replaceHtml
        data-ajax-container: 'span#content-wrapper'
        data-ajax-then: afterSaveCallback
        action: delete
      dropdown: false
    - dropdown: true
      options:
      - label: View Details
        data:
          action: view
      - label: Send Email
        data:
          action: email"
  headers:
  - name: "id"
    key: "id"
    orderable: true
    searchable: true
    visible: true
  - name: "name"
    key: "name"
    orderable: true
    searchable: true
    visible: true
  - name: 'created_at'
    key: "created_at"
    orderable: true
    searchable: true
    visible: true
  - name: 'updated_at'
    key: "updated_at"
    orderable: true
    searchable: true
    visible: true
  - name: 'actions'
    key: "actions"
    orderable: false
    searchable: false
    visible: true
    actions:
      - name: "View"
        icon: "ri-eye-line"
        action: "view"
      - name: "Edit"
        icon: "ri-pencil-line"
        action: "edit"
      - name: "Delete"
        icon: "ri-delete-bin-line"
        action: "delete"
inputs:
  - type: hidden
    name: id
    value: 0
    col: 12
  - type: text
    name: name
    label: name
    data:
      fs-validate: "true"
      fs-required: "true"
      fs-error-required: patient.firstname_required
    value: ''
    col: 6
    placeholder: John
form:
  id: 'patient_form'
  title: add_patient
  file: 'patient'
  source: /patients/save
  method: replaceHtml
  container: 'span#content-wrapper'
  then: afterSaveCallback