table:
  name: "Users"
  id: "user_table"
  path: '/users/data'
  file: 'user'
  actions:
    - class: btn-edit
      icon: edit
      data:
        data-ajax-source: /users/form/{0}
        data-ajax-method: replaceHtml
        data-ajax-container: '#offcanvasEnd'
        data-bs-toggle: "offcanvas" 
        data-bs-target: "#offcanvasEnd"
        aria-controls: "offcanvasEnd"
        action: edit
    - class: btn-delete
      icon: delete-bin-5
      data:
        data-ajax-source: /users/delete/{0}
        data-ajax-method: replaceHtml
        data-ajax-container: 'span#content-wrapper'
        data-ajax-then: afterSaveCallback
        action: delete
      dropdown: false
    - dropdown: true
      options:
      - label: View Details
        data:
          data-ajax-source: /users/view/{0}
          data-ajax-method: replaceHtml
          data-ajax-container: '#offcanvasEnd'
          data-bs-toggle: "offcanvas" 
          data-bs-target: "#offcanvasEnd"
          aria-controls: "offcanvasEnd"
          action: view
      - label: Send Email
        data:
          id: 1
          action: email"
  headers:
  - name: "id"
    key: "id"
    orderable: true
    searchable: true
    visible: true
  - name: "name"
    key: "firstname"
    orderable: true
    searchable: true
    visible: true
  - name: "lastname"
    key: "lastname"
    orderable: true
    searchable: true
    visible: false
  - name: "email"
    key: "email"
    orderable: true
    searchable: true
    visible: true
  - name: status
    key: status_name
    orderable: true
    searchable: true
    visible: true
  - name: 'actions'
    key: "actions"
    orderable: false
    searchable: false
    visible: true
    actions:
      - name: "View"
        icon: "ri-eye-line"
        action: "view"
      - name: "Edit"
        icon: "ri-pencil-line"
        action: "edit"
      - name: "Delete"
        icon: "ri-delete-bin-line"
        action: "delete"
inputs:
  - type: hidden
    name: id
    value: 0
    col: 12
  - type: text
    name: firstname
    label: firstname
    data:
      fs-validate: "true"
      fs-required: "true"
      fs-minlength: 3
      fs-error-required: user.firstname_required
      fs-error-minlength: user.firstname_minlength
    value: ''
    placeholder: John
    col: 12
  - type: text
    name: lastname
    label: lastname
    data:
      fs-validate: "true"
      fs-required: "true"
      fs-minlength: 3
      fs-error-required: user.lastname_required
      fs-error-minlength: user.lastname_minlength
    value: ''
    col: 12
    placeholder: Doe
  - type: email
    name: email
    label: email
    data:
      fs-validate: "true"
      fs-required: "true"
      fs-email: "true"
      fs-remote: "true"
      fs-error-required: user.email_required
      fs-error-email: user.email_invalid
    value: ''
    col: 12
    placeholder: johndoe@mail.com
  - type: password
    name: password
    label: password
    data:
      fs-validate: "true"
      fs-minlength: 8
      fs-pattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^a-zA-Z\d]).{8,}$
      fs-error-pattern: user.password_pattern
      fs-error-minlength: user.password_minlength
    value: ''
    col: 12
form:
  id: 'user_form'
  file: 'user'
  title: form_title
  source: /users/save
  method: replaceHtml
  container: 'span#content-wrapper'
  then: afterSaveCallback