table:
  name: "Users"
  id: "user_table"
  path: '/users/data'
  actions:
    - class: btn-edit
      icon: edit
      data:
        data-ajax-source: /users/form/{0}
        data-ajax-method: replaceHtml
        data-ajax-container: '#offcanvasEnd'
        data-bs-toggle: "offcanvas" 
        data-bs-target: "#offcanvasEnd"
        aria-controls: "offcanvasEnd"
        action: edit
    - class: btn-delete
      icon: delete-bin-5
      data:
        data-ajax-source: /users/delete/{0}
        data-ajax-method: replaceHtml
        data-ajax-container: 'span#content-wrapper'
        data-ajax-then: afterSaveCallback
        action: delete
      dropdown: false
    - dropdown: true
      options:
      - label: View Details
        data:
          data-ajax-source: /users/view/{0}
          data-ajax-method: replaceHtml
          data-ajax-container: '#offcanvasEnd'
          data-bs-toggle: "offcanvas" 
          data-bs-target: "#offcanvasEnd"
          aria-controls: "offcanvasEnd"
          action: view
      - label: Send Email
        data:
          id: 1
          action: email"
  headers:
  - name: "ID"
    key: "id"
    orderable: true
    searchable: true
    visible: true
  - name: "Firstname"
    key: "firstname"
    orderable: true
    searchable: true
    visible: true
  - name: "Lastname"
    key: "lastname"
    orderable: true
    searchable: true
    visible: true
  - name: "Email"
    key: "email"
    orderable: true
    searchable: true
    visible: true
  - name: Status
    key: status_name
    orderable: true
    searchable: true
    visible: true
  - name: 'actions'
    key: "actions"
    orderable: false
    searchable: false
    visible: true
    actions:
      - name: "View"
        icon: "ri-eye-line"
        action: "view"
      - name: "Edit"
        icon: "ri-pencil-line"
        action: "edit"
      - name: "Delete"
        icon: "ri-delete-bin-line"
        action: "delete"
inputs:
  - type: hidden
    name: id
    value: 0
    col: 12
  - type: text
    name: firstname
    label: Firstname
    value: ''
    placeholder: John
    col: 12
  - type: text
    name: lastname
    label: Lastname
    value: ''
    col: 12
    placeholder: Doe
  - type: email
    name: email
    label: Email
    value: ''
    col: 12
    placeholder: johndoe@mail.com
  - type: password
    name: password
    label: Password
    value: ''
    col: 12
form:
  id: 'user_form'
  title: Add user
  source: /users/save
  method: replaceHtml
  container: 'span#content-wrapper'
  then: afterSaveCallback